# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{serialist}
  s.version = "0.5.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benoit B\303\251n\303\251zech"]
  s.date = %q{2009-09-17}
  s.description = %q{Serialize any data, set and fetch it like any column attributes}
  s.email = %q{benoit.benezech@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO.txt",
     "VERSION",
     "generators/serialist/serialist_generator.rb",
     "generators/serialist/templates/USAGE",
     "generators/serialist/templates/migrate/serialist_migration.rb.erb",
     "init.rb",
     "install.rb",
     "installation-template.txt",
     "lib/serialist.rb",
     "lib/serialist/serialist_module.rb",
     "rails/init.rb",
     "serialist.gemspec",
     "tasks/acts_as_serializable_tasks.rake",
     "test/acts_as_serializable_test.rb",
     "test/test_helper.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/bbenezech/serialist}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.4}
  s.summary = %q{Serialize any data, set and fetch it like any column attributes}
  s.test_files = [
    "test/acts_as_serializable_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
